// seed-rooms.js
const axios = require("axios");
const mongoose = require("mongoose");
require("dotenv").config();

// Your rooms data (paste the complete array from the previous message)
const rooms = [
  {
    name: "315",
    displayName: "315",
    slug: "executive-315",
    roomNumber: "315",
    category: "Executive",
    pricePerNight: 37450,
    maxGuests: 2,
    maxAdults: 2,
    maxChildren: 0,
    bedType: "Queen",
    bedCount: 1,
    bathrooms: 1,
    size: "32 m²",
    sizeValue: 32,
    floor: 3,
    view: "City View",
    description: "Luxurious executive accommodation with modern amenities",
    longDescription:
      "Experience comfort and luxury in our beautifully appointed executive room. Features include a comfortable queen-sized bed, high-speed WiFi, and elegant furnishings.",
    amenities: [
      { label: "WiFi", icon: "FaWifi", category: "technology" },
      { label: "Air Conditioning", icon: "FaSnowflake", category: "comfort" },
      { label: "Flat-screen TV", icon: "FaTv", category: "technology" },
      { label: "Mini Bar", icon: "FaGlassCheers", category: "dining" },
    ],
    includes: ["Breakfast", "Welcome Drink"],
    tags: ["executive", "queen", "city-view"],
    isAvailable: true,
    isPublished: true,
  },
  {
    name: "406",
    displayName: "406",
    slug: "executive-406",
    roomNumber: "406",
    category: "Executive",
    pricePerNight: 37450,
    maxGuests: 2,
    maxAdults: 2,
    maxChildren: 0,
    bedType: "Queen",
    bedCount: 1,
    bathrooms: 1,
    size: "32 m²",
    sizeValue: 32,
    floor: 4,
    view: "City View",
    description: "Luxurious executive accommodation with modern amenities",
    longDescription:
      "Experience comfort and luxury in our beautifully appointed executive room. Features include a comfortable queen-sized bed, high-speed WiFi, and elegant furnishings.",
    amenities: [
      { label: "WiFi", icon: "FaWifi", category: "technology" },
      { label: "Air Conditioning", icon: "FaSnowflake", category: "comfort" },
      { label: "Flat-screen TV", icon: "FaTv", category: "technology" },
      { label: "Mini Bar", icon: "FaGlassCheers", category: "dining" },
    ],
    includes: ["Breakfast", "Welcome Drink"],
    tags: ["executive", "queen", "city-view"],
    isAvailable: true,
    isPublished: true,
  },
  {
    name: "408",
    displayName: "408",
    slug: "executive-408",
    roomNumber: "408",
    category: "Executive",
    pricePerNight: 37450,
    maxGuests: 2,
    maxAdults: 2,
    maxChildren: 0,
    bedType: "Queen",
    bedCount: 1,
    bathrooms: 1,
    size: "32 m²",
    sizeValue: 32,
    floor: 4,
    view: "City View",
    description: "Luxurious executive accommodation with modern amenities",
    longDescription:
      "Experience comfort and luxury in our beautifully appointed executive room. Features include a comfortable queen-sized bed, high-speed WiFi, and elegant furnishings.",
    amenities: [
      { label: "WiFi", icon: "FaWifi", category: "technology" },
      { label: "Air Conditioning", icon: "FaSnowflake", category: "comfort" },
      { label: "Flat-screen TV", icon: "FaTv", category: "technology" },
      { label: "Mini Bar", icon: "FaGlassCheers", category: "dining" },
    ],
    includes: ["Breakfast", "Welcome Drink"],
    tags: ["executive", "queen", "city-view"],
    isAvailable: true,
    isPublished: true,
  },
  {
    name: "507",
    displayName: "507",
    slug: "executive-507",
    roomNumber: "507",
    category: "Executive",
    pricePerNight: 37450,
    maxGuests: 2,
    maxAdults: 2,
    maxChildren: 0,
    bedType: "Queen",
    bedCount: 1,
    bathrooms: 1,
    size: "32 m²",
    sizeValue: 32,
    floor: 5,
    view: "City View",
    description: "Luxurious executive accommodation with modern amenities",
    longDescription:
      "Experience comfort and luxury in our beautifully appointed executive room. Features include a comfortable queen-sized bed, high-speed WiFi, and elegant furnishings.",
    amenities: [
      { label: "WiFi", icon: "FaWifi", category: "technology" },
      { label: "Air Conditioning", icon: "FaSnowflake", category: "comfort" },
      { label: "Flat-screen TV", icon: "FaTv", category: "technology" },
      { label: "Mini Bar", icon: "FaGlassCheers", category: "dining" },
    ],
    includes: ["Breakfast", "Welcome Drink"],
    tags: ["executive", "queen", "city-view"],
    isAvailable: true,
    isPublished: true,
  },
  {
    name: "508",
    displayName: "508",
    slug: "executive-508",
    roomNumber: "508",
    category: "Executive",
    pricePerNight: 37450,
    maxGuests: 2,
    maxAdults: 2,
    maxChildren: 0,
    bedType: "Queen",
    bedCount: 1,
    bathrooms: 1,
    size: "32 m²",
    sizeValue: 32,
    floor: 5,
    view: "City View",
    description: "Luxurious executive accommodation with modern amenities",
    longDescription:
      "Experience comfort and luxury in our beautifully appointed executive room. Features include a comfortable queen-sized bed, high-speed WiFi, and elegant furnishings.",
    amenities: [
      { label: "WiFi", icon: "FaWifi", category: "technology" },
      { label: "Air Conditioning", icon: "FaSnowflake", category: "comfort" },
      { label: "Flat-screen TV", icon: "FaTv", category: "technology" },
      { label: "Mini Bar", icon: "FaGlassCheers", category: "dining" },
    ],
    includes: ["Breakfast", "Welcome Drink"],
    tags: ["executive", "queen", "city-view"],
    isAvailable: true,
    isPublished: true,
  },
  {
    name: "514",
    displayName: "514",
    slug: "executive-514",
    roomNumber: "514",
    category: "Executive",
    pricePerNight: 37450,
    maxGuests: 2,
    maxAdults: 2,
    maxChildren: 0,
    bedType: "Queen",
    bedCount: 1,
    bathrooms: 1,
    size: "32 m²",
    sizeValue: 32,
    floor: 5,
    view: "City View",
    description: "Luxurious executive accommodation with modern amenities",
    longDescription:
      "Experience comfort and luxury in our beautifully appointed executive room. Features include a comfortable queen-sized bed, high-speed WiFi, and elegant furnishings.",
    amenities: [
      { label: "WiFi", icon: "FaWifi", category: "technology" },
      { label: "Air Conditioning", icon: "FaSnowflake", category: "comfort" },
      { label: "Flat-screen TV", icon: "FaTv", category: "technology" },
      { label: "Mini Bar", icon: "FaGlassCheers", category: "dining" },
    ],
    includes: ["Breakfast", "Welcome Drink"],
    tags: ["executive", "queen", "city-view"],
    isAvailable: true,
    isPublished: true,
  },
  {
    name: "515",
    displayName: "515",
    slug: "executive-515",
    roomNumber: "515",
    category: "Executive",
    pricePerNight: 37450,
    maxGuests: 2,
    maxAdults: 2,
    maxChildren: 0,
    bedType: "Queen",
    bedCount: 1,
    bathrooms: 1,
    size: "32 m²",
    sizeValue: 32,
    floor: 5,
    view: "City View",
    description: "Luxurious executive accommodation with modern amenities",
    longDescription:
      "Experience comfort and luxury in our beautifully appointed executive room. Features include a comfortable queen-sized bed, high-speed WiFi, and elegant furnishings.",
    amenities: [
      { label: "WiFi", icon: "FaWifi", category: "technology" },
      { label: "Air Conditioning", icon: "FaSnowflake", category: "comfort" },
      { label: "Flat-screen TV", icon: "FaTv", category: "technology" },
      { label: "Mini Bar", icon: "FaGlassCheers", category: "dining" },
    ],
    includes: ["Breakfast", "Welcome Drink"],
    tags: ["executive", "queen", "city-view"],
    isAvailable: true,
    isPublished: true,
  },
  {
    name: "GREEN - 306",
    displayName: "GREEN - 306",
    slug: "executive-green-306",
    roomNumber: "306",
    category: "Executive",
    pricePerNight: 37450,
    maxGuests: 2,
    maxAdults: 2,
    maxChildren: 0,
    bedType: "Queen",
    bedCount: 1,
    bathrooms: 1,
    size: "32 m²",
    sizeValue: 32,
    floor: 3,
    view: "City View",
    description: "Luxurious executive accommodation with modern amenities",
    longDescription:
      "Experience comfort and luxury in our beautifully appointed executive room with a green theme. Features include a comfortable queen-sized bed, high-speed WiFi, and elegant furnishings.",
    amenities: [
      { label: "WiFi", icon: "FaWifi", category: "technology" },
      { label: "Air Conditioning", icon: "FaSnowflake", category: "comfort" },
      { label: "Flat-screen TV", icon: "FaTv", category: "technology" },
      { label: "Mini Bar", icon: "FaGlassCheers", category: "dining" },
    ],
    includes: ["Breakfast", "Welcome Drink"],
    tags: ["executive", "queen", "green-theme"],
    isAvailable: true,
    isPublished: true,
  },
  {
    name: "GREY - 307",
    displayName: "GREY - 307",
    slug: "executive-grey-307",
    roomNumber: "307",
    category: "Executive",
    pricePerNight: 37450,
    maxGuests: 2,
    maxAdults: 2,
    maxChildren: 0,
    bedType: "Queen",
    bedCount: 1,
    bathrooms: 1,
    size: "32 m²",
    sizeValue: 32,
    floor: 3,
    view: "City View",
    description: "Luxurious executive accommodation with modern amenities",
    longDescription:
      "Experience comfort and luxury in our beautifully appointed executive room with a grey theme. Features include a comfortable queen-sized bed, high-speed WiFi, and elegant furnishings.",
    amenities: [
      { label: "WiFi", icon: "FaWifi", category: "technology" },
      { label: "Air Conditioning", icon: "FaSnowflake", category: "comfort" },
      { label: "Flat-screen TV", icon: "FaTv", category: "technology" },
      { label: "Mini Bar", icon: "FaGlassCheers", category: "dining" },
    ],
    includes: ["Breakfast", "Welcome Drink"],
    tags: ["executive", "queen", "grey-theme"],
    isAvailable: true,
    isPublished: true,
  },
  {
    name: "HAWK - 407",
    displayName: "HAWK - 407",
    slug: "executive-hawk-407",
    roomNumber: "407",
    category: "Executive",
    pricePerNight: 37450,
    maxGuests: 2,
    maxAdults: 2,
    maxChildren: 0,
    bedType: "Queen",
    bedCount: 1,
    bathrooms: 1,
    size: "32 m²",
    sizeValue: 32,
    floor: 4,
    view: "City View",
    description: "Luxurious executive accommodation with modern amenities",
    longDescription:
      "Experience comfort and luxury in our beautifully appointed executive room with a hawk theme. Features include a comfortable queen-sized bed, high-speed WiFi, and elegant furnishings.",
    amenities: [
      { label: "WiFi", icon: "FaWifi", category: "technology" },
      { label: "Air Conditioning", icon: "FaSnowflake", category: "comfort" },
      { label: "Flat-screen TV", icon: "FaTv", category: "technology" },
      { label: "Mini Bar", icon: "FaGlassCheers", category: "dining" },
    ],
    includes: ["Breakfast", "Welcome Drink"],
    tags: ["executive", "queen", "bird-theme"],
    isAvailable: true,
    isPublished: true,
  },
  {
    name: "IBIZA - 506",
    displayName: "IBIZA - 506",
    slug: "executive-ibiza-506",
    roomNumber: "506",
    category: "Executive",
    pricePerNight: 37450,
    maxGuests: 2,
    maxAdults: 2,
    maxChildren: 0,
    bedType: "Queen",
    bedCount: 1,
    bathrooms: 1,
    size: "32 m²",
    sizeValue: 32,
    floor: 5,
    view: "City View",
    description: "Luxurious executive accommodation with modern amenities",
    longDescription:
      "Experience comfort and luxury in our beautifully appointed executive room with an Ibiza theme. Features include a comfortable queen-sized bed, high-speed WiFi, and elegant furnishings.",
    amenities: [
      { label: "WiFi", icon: "FaWifi", category: "technology" },
      { label: "Air Conditioning", icon: "FaSnowflake", category: "comfort" },
      { label: "Flat-screen TV", icon: "FaTv", category: "technology" },
      { label: "Mini Bar", icon: "FaGlassCheers", category: "dining" },
    ],
    includes: ["Breakfast", "Welcome Drink"],
    tags: ["executive", "queen", "destination-theme"],
    isAvailable: true,
    isPublished: true,
  },
  {
    name: "INDIGO - 308",
    displayName: "INDIGO - 308",
    slug: "executive-indigo-308",
    roomNumber: "308",
    category: "Executive",
    pricePerNight: 37450,
    maxGuests: 2,
    maxAdults: 2,
    maxChildren: 0,
    bedType: "Queen",
    bedCount: 1,
    bathrooms: 1,
    size: "32 m²",
    sizeValue: 32,
    floor: 3,
    view: "City View",
    description: "Luxurious executive accommodation with modern amenities",
    longDescription:
      "Experience comfort and luxury in our beautifully appointed executive room with an indigo theme. Features include a comfortable queen-sized bed, high-speed WiFi, and elegant furnishings.",
    amenities: [
      { label: "WiFi", icon: "FaWifi", category: "technology" },
      { label: "Air Conditioning", icon: "FaSnowflake", category: "comfort" },
      { label: "Flat-screen TV", icon: "FaTv", category: "technology" },
      { label: "Mini Bar", icon: "FaGlassCheers", category: "dining" },
    ],
    includes: ["Breakfast", "Welcome Drink"],
    tags: ["executive", "queen", "color-theme"],
    isAvailable: true,
    isPublished: true,
  },
  {
    name: "MARS - 606",
    displayName: "MARS - 606",
    slug: "executive-mars-606",
    roomNumber: "606",
    category: "Executive",
    pricePerNight: 37450,
    maxGuests: 2,
    maxAdults: 2,
    maxChildren: 0,
    bedType: "Queen",
    bedCount: 1,
    bathrooms: 1,
    size: "32 m²",
    sizeValue: 32,
    floor: 6,
    view: "City View",
    description: "Luxurious executive accommodation with modern amenities",
    longDescription:
      "Experience comfort and luxury in our beautifully appointed executive room with a Mars theme. Features include a comfortable queen-sized bed, high-speed WiFi, and elegant furnishings.",
    amenities: [
      { label: "WiFi", icon: "FaWifi", category: "technology" },
      { label: "Air Conditioning", icon: "FaSnowflake", category: "comfort" },
      { label: "Flat-screen TV", icon: "FaTv", category: "technology" },
      { label: "Mini Bar", icon: "FaGlassCheers", category: "dining" },
    ],
    includes: ["Breakfast", "Welcome Drink"],
    tags: ["executive", "queen", "space-theme"],
    isAvailable: true,
    isPublished: true,
  },
  {
    name: "MERCURY - 607",
    displayName: "MERCURY - 607",
    slug: "executive-mercury-607",
    roomNumber: "607",
    category: "Executive",
    pricePerNight: 37450,
    maxGuests: 2,
    maxAdults: 2,
    maxChildren: 0,
    bedType: "Queen",
    bedCount: 1,
    bathrooms: 1,
    size: "32 m²",
    sizeValue: 32,
    floor: 6,
    view: "City View",
    description: "Luxurious executive accommodation with modern amenities",
    longDescription:
      "Experience comfort and luxury in our beautifully appointed executive room with a Mercury theme. Features include a comfortable queen-sized bed, high-speed WiFi, and elegant furnishings.",
    amenities: [
      { label: "WiFi", icon: "FaWifi", category: "technology" },
      { label: "Air Conditioning", icon: "FaSnowflake", category: "comfort" },
      { label: "Flat-screen TV", icon: "FaTv", category: "technology" },
      { label: "Mini Bar", icon: "FaGlassCheers", category: "dining" },
    ],
    includes: ["Breakfast", "Welcome Drink"],
    tags: ["executive", "queen", "space-theme"],
    isAvailable: true,
    isPublished: true,
  },
  {
    name: "AC MILAN - 101",
    displayName: "AC MILAN - 101",
    slug: "annex-classic-ac-milan-101",
    roomNumber: "101",
    category: "Annex - Classic",
    pricePerNight: 16050,
    maxGuests: 2,
    maxAdults: 2,
    maxChildren: 0,
    bedType: "Queen",
    bedCount: 1,
    bathrooms: 1,
    size: "25 m²",
    sizeValue: 25,
    floor: 1,
    view: "Garden View",
    description: "Classic annex accommodation with modern amenities",
    longDescription:
      "Experience comfort in our classic annex room with an AC Milan theme. Features include a comfortable queen-sized bed, high-speed WiFi, and elegant furnishings.",
    amenities: [
      { label: "WiFi", icon: "FaWifi", category: "technology" },
      { label: "Air Conditioning", icon: "FaSnowflake", category: "comfort" },
      { label: "Flat-screen TV", icon: "FaTv", category: "technology" },
    ],
    includes: ["Breakfast"],
    tags: ["annex", "classic", "football-theme"],
    isAvailable: true,
    isPublished: true,
  },
  {
    name: "BARCELONA - 103",
    displayName: "BARCELONA - 103",
    slug: "annex-classic-barcelona-103",
    roomNumber: "103",
    category: "Annex - Classic",
    pricePerNight: 16050,
    maxGuests: 2,
    maxAdults: 2,
    maxChildren: 0,
    bedType: "Queen",
    bedCount: 1,
    bathrooms: 1,
    size: "25 m²",
    sizeValue: 25,
    floor: 1,
    view: "Garden View",
    description: "Classic annex accommodation with modern amenities",
    longDescription:
      "Experience comfort in our classic annex room with a Barcelona theme. Features include a comfortable queen-sized bed, high-speed WiFi, and elegant furnishings.",
    amenities: [
      { label: "WiFi", icon: "FaWifi", category: "technology" },
      { label: "Air Conditioning", icon: "FaSnowflake", category: "comfort" },
      { label: "Flat-screen TV", icon: "FaTv", category: "technology" },
    ],
    includes: ["Breakfast"],
    tags: ["annex", "classic", "football-theme"],
    isAvailable: true,
    isPublished: true,
  },
  {
    name: "BAYERN MUNICH - 104",
    displayName: "BAYERN MUNICH - 104",
    slug: "annex-classic-bayern-104",
    roomNumber: "104",
    category: "Annex - Classic",
    pricePerNight: 16050,
    maxGuests: 2,
    maxAdults: 2,
    maxChildren: 0,
    bedType: "Queen",
    bedCount: 1,
    bathrooms: 1,
    size: "25 m²",
    sizeValue: 25,
    floor: 1,
    view: "Garden View",
    description: "Classic annex accommodation with modern amenities",
    longDescription:
      "Experience comfort in our classic annex room with a Bayern Munich theme. Features include a comfortable queen-sized bed, high-speed WiFi, and elegant furnishings.",
    amenities: [
      { label: "WiFi", icon: "FaWifi", category: "technology" },
      { label: "Air Conditioning", icon: "FaSnowflake", category: "comfort" },
      { label: "Flat-screen TV", icon: "FaTv", category: "technology" },
    ],
    includes: ["Breakfast"],
    tags: ["annex", "classic", "football-theme"],
    isAvailable: true,
    isPublished: true,
  },
  {
    name: "FRANKFURT - 206",
    displayName: "FRANKFURT - 206",
    slug: "annex-classic-frankfurt-206",
    roomNumber: "206",
    category: "Annex - Classic",
    pricePerNight: 16050,
    maxGuests: 2,
    maxAdults: 2,
    maxChildren: 0,
    bedType: "Queen",
    bedCount: 1,
    bathrooms: 1,
    size: "25 m²",
    sizeValue: 25,
    floor: 2,
    view: "Garden View",
    description: "Classic annex accommodation with modern amenities",
    longDescription:
      "Experience comfort in our classic annex room with a Frankfurt theme. Features include a comfortable queen-sized bed, high-speed WiFi, and elegant furnishings.",
    amenities: [
      { label: "WiFi", icon: "FaWifi", category: "technology" },
      { label: "Air Conditioning", icon: "FaSnowflake", category: "comfort" },
      { label: "Flat-screen TV", icon: "FaTv", category: "technology" },
    ],
    includes: ["Breakfast"],
    tags: ["annex", "classic", "football-theme"],
    isAvailable: true,
    isPublished: true,
  },
  {
    name: "LIVERPOOL - 109",
    displayName: "LIVERPOOL - 109",
    slug: "annex-classic-liverpool-109",
    roomNumber: "109",
    category: "Annex - Classic",
    pricePerNight: 16050,
    maxGuests: 2,
    maxAdults: 2,
    maxChildren: 0,
    bedType: "Queen",
    bedCount: 1,
    bathrooms: 1,
    size: "25 m²",
    sizeValue: 25,
    floor: 1,
    view: "Garden View",
    description: "Classic annex accommodation with modern amenities",
    longDescription:
      "Experience comfort in our classic annex room with a Liverpool theme. Features include a comfortable queen-sized bed, high-speed WiFi, and elegant furnishings.",
    amenities: [
      { label: "WiFi", icon: "FaWifi", category: "technology" },
      { label: "Air Conditioning", icon: "FaSnowflake", category: "comfort" },
      { label: "Flat-screen TV", icon: "FaTv", category: "technology" },
    ],
    includes: ["Breakfast"],
    tags: ["annex", "classic", "football-theme"],
    isAvailable: true,
    isPublished: true,
  },
  {
    name: "MAN CITY - 110",
    displayName: "MAN CITY - 110",
    slug: "annex-classic-mancity-110",
    roomNumber: "110",
    category: "Annex - Classic",
    pricePerNight: 16050,
    maxGuests: 2,
    maxAdults: 2,
    maxChildren: 0,
    bedType: "Queen",
    bedCount: 1,
    bathrooms: 1,
    size: "25 m²",
    sizeValue: 25,
    floor: 1,
    view: "Garden View",
    description: "Classic annex accommodation with modern amenities",
    longDescription:
      "Experience comfort in our classic annex room with a Manchester City theme. Features include a comfortable queen-sized bed, high-speed WiFi, and elegant furnishings.",
    amenities: [
      { label: "WiFi", icon: "FaWifi", category: "technology" },
      { label: "Air Conditioning", icon: "FaSnowflake", category: "comfort" },
      { label: "Flat-screen TV", icon: "FaTv", category: "technology" },
    ],
    includes: ["Breakfast"],
    tags: ["annex", "classic", "football-theme"],
    isAvailable: true,
    isPublished: true,
  },
  {
    name: "MONACO - 208",
    displayName: "MONACO - 208",
    slug: "annex-classic-monaco-208",
    roomNumber: "208",
    category: "Annex - Classic",
    pricePerNight: 16050,
    maxGuests: 2,
    maxAdults: 2,
    maxChildren: 0,
    bedType: "Queen",
    bedCount: 1,
    bathrooms: 1,
    size: "25 m²",
    sizeValue: 25,
    floor: 2,
    view: "Garden View",
    description: "Classic annex accommodation with modern amenities",
    longDescription:
      "Experience comfort in our classic annex room with a Monaco theme. Features include a comfortable queen-sized bed, high-speed WiFi, and elegant furnishings.",
    amenities: [
      { label: "WiFi", icon: "FaWifi", category: "technology" },
      { label: "Air Conditioning", icon: "FaSnowflake", category: "comfort" },
      { label: "Flat-screen TV", icon: "FaTv", category: "technology" },
    ],
    includes: ["Breakfast"],
    tags: ["annex", "classic", "monaco-theme"],
    isAvailable: true,
    isPublished: true,
  },
  {
    name: "ACAPULCO - 501",
    displayName: "ACAPULCO - 501",
    slug: "imperial-suite-acapulco-501",
    roomNumber: "501",
    category: "Imperial Suite",
    pricePerNight: 58850,
    maxGuests: 4,
    maxAdults: 4,
    maxChildren: 0,
    bedType: "King",
    bedCount: 2,
    bathrooms: 2,
    size: "65 m²",
    sizeValue: 65,
    floor: 5,
    view: "Ocean View",
    description: "Luxurious imperial suite with premium amenities",
    longDescription:
      "Experience the ultimate luxury in our imperial suite with an Acapulco theme. Features include two king-sized beds, separate living area, premium amenities, and stunning ocean views.",
    amenities: [
      { label: "WiFi", icon: "FaWifi", category: "technology" },
      { label: "Air Conditioning", icon: "FaSnowflake", category: "comfort" },
      { label: "Flat-screen TV", icon: "FaTv", category: "technology" },
      { label: "Mini Bar", icon: "FaGlassCheers", category: "dining" },
      { label: "Jacuzzi", icon: "FaHotTub", category: "bathroom" },
      { label: "Living Area", icon: "FaCouch", category: "comfort" },
    ],
    includes: ["Breakfast", "Welcome Drink", "Airport Transfer"],
    tags: ["suite", "imperial", "luxury", "king", "ocean-view"],
    isAvailable: true,
    isPublished: true,
  },
  {
    name: "BENTLEY - 201",
    displayName: "BENTLEY - 201",
    slug: "imperial-suite-bentley-201",
    roomNumber: "201",
    category: "Imperial Suite",
    pricePerNight: 58850,
    maxGuests: 4,
    maxAdults: 4,
    maxChildren: 0,
    bedType: "King",
    bedCount: 2,
    bathrooms: 2,
    size: "65 m²",
    sizeValue: 65,
    floor: 2,
    view: "Ocean View",
    description: "Luxurious imperial suite with premium amenities",
    longDescription:
      "Experience the ultimate luxury in our imperial suite with a Bentley theme. Features include two king-sized beds, separate living area, premium amenities, and stunning ocean views.",
    amenities: [
      { label: "WiFi", icon: "FaWifi", category: "technology" },
      { label: "Air Conditioning", icon: "FaSnowflake", category: "comfort" },
      { label: "Flat-screen TV", icon: "FaTv", category: "technology" },
      { label: "Mini Bar", icon: "FaGlassCheers", category: "dining" },
      { label: "Jacuzzi", icon: "FaHotTub", category: "bathroom" },
      { label: "Living Area", icon: "FaCouch", category: "comfort" },
    ],
    includes: ["Breakfast", "Welcome Drink", "Airport Transfer"],
    tags: ["suite", "imperial", "luxury", "king", "ocean-view"],
    isAvailable: true,
    isPublished: true,
  },
  {
    name: "BLACK - 301",
    displayName: "BLACK - 301",
    slug: "imperial-suite-black-301",
    roomNumber: "301",
    category: "Imperial Suite",
    pricePerNight: 58850,
    maxGuests: 4,
    maxAdults: 4,
    maxChildren: 0,
    bedType: "King",
    bedCount: 2,
    bathrooms: 2,
    size: "65 m²",
    sizeValue: 65,
    floor: 3,
    view: "Ocean View",
    description: "Luxurious imperial suite with premium amenities",
    longDescription:
      "Experience the ultimate luxury in our imperial suite with a black theme. Features include two king-sized beds, separate living area, premium amenities, and stunning ocean views.",
    amenities: [
      { label: "WiFi", icon: "FaWifi", category: "technology" },
      { label: "Air Conditioning", icon: "FaSnowflake", category: "comfort" },
      { label: "Flat-screen TV", icon: "FaTv", category: "technology" },
      { label: "Mini Bar", icon: "FaGlassCheers", category: "dining" },
      { label: "Jacuzzi", icon: "FaHotTub", category: "bathroom" },
      { label: "Living Area", icon: "FaCouch", category: "comfort" },
    ],
    includes: ["Breakfast", "Welcome Drink", "Airport Transfer"],
    tags: ["suite", "imperial", "luxury", "king", "ocean-view"],
    isAvailable: true,
    isPublished: true,
  },
  {
    name: "CANARY - 401",
    displayName: "CANARY - 401",
    slug: "imperial-suite-canary-401",
    roomNumber: "401",
    category: "Imperial Suite",
    pricePerNight: 58850,
    maxGuests: 4,
    maxAdults: 4,
    maxChildren: 0,
    bedType: "King",
    bedCount: 2,
    bathrooms: 2,
    size: "65 m²",
    sizeValue: 65,
    floor: 4,
    view: "Ocean View",
    description: "Luxurious imperial suite with premium amenities",
    longDescription:
      "Experience the ultimate luxury in our imperial suite with a canary theme. Features include two king-sized beds, separate living area, premium amenities, and stunning ocean views.",
    amenities: [
      { label: "WiFi", icon: "FaWifi", category: "technology" },
      { label: "Air Conditioning", icon: "FaSnowflake", category: "comfort" },
      { label: "Flat-screen TV", icon: "FaTv", category: "technology" },
      { label: "Mini Bar", icon: "FaGlassCheers", category: "dining" },
      { label: "Jacuzzi", icon: "FaHotTub", category: "bathroom" },
      { label: "Living Area", icon: "FaCouch", category: "comfort" },
    ],
    includes: ["Breakfast", "Welcome Drink", "Airport Transfer"],
    tags: ["suite", "imperial", "luxury", "king", "ocean-view"],
    isAvailable: true,
    isPublished: true,
  },
  {
    name: "FALCON - 405",
    displayName: "FALCON - 405",
    slug: "imperial-suite-falcon-405",
    roomNumber: "405",
    category: "Imperial Suite",
    pricePerNight: 58850,
    maxGuests: 4,
    maxAdults: 4,
    maxChildren: 0,
    bedType: "King",
    bedCount: 2,
    bathrooms: 2,
    size: "65 m²",
    sizeValue: 65,
    floor: 4,
    view: "Ocean View",
    description: "Luxurious imperial suite with premium amenities",
    longDescription:
      "Experience the ultimate luxury in our imperial suite with a falcon theme. Features include two king-sized beds, separate living area, premium amenities, and stunning ocean views.",
    amenities: [
      { label: "WiFi", icon: "FaWifi", category: "technology" },
      { label: "Air Conditioning", icon: "FaSnowflake", category: "comfort" },
      { label: "Flat-screen TV", icon: "FaTv", category: "technology" },
      { label: "Mini Bar", icon: "FaGlassCheers", category: "dining" },
      { label: "Jacuzzi", icon: "FaHotTub", category: "bathroom" },
      { label: "Living Area", icon: "FaCouch", category: "comfort" },
    ],
    includes: ["Breakfast", "Welcome Drink", "Airport Transfer"],
    tags: ["suite", "imperial", "luxury", "king", "ocean-view"],
    isAvailable: true,
    isPublished: true,
  },
  {
    name: "GOLD - 305",
    displayName: "GOLD - 305",
    slug: "imperial-suite-gold-305",
    roomNumber: "305",
    category: "Imperial Suite",
    pricePerNight: 58850,
    maxGuests: 4,
    maxAdults: 4,
    maxChildren: 0,
    bedType: "King",
    bedCount: 2,
    bathrooms: 2,
    size: "65 m²",
    sizeValue: 65,
    floor: 3,
    view: "Ocean View",
    description: "Luxurious imperial suite with premium amenities",
    longDescription:
      "Experience the ultimate luxury in our imperial suite with a gold theme. Features include two king-sized beds, separate living area, premium amenities, and stunning ocean views.",
    amenities: [
      { label: "WiFi", icon: "FaWifi", category: "technology" },
      { label: "Air Conditioning", icon: "FaSnowflake", category: "comfort" },
      { label: "Flat-screen TV", icon: "FaTv", category: "technology" },
      { label: "Mini Bar", icon: "FaGlassCheers", category: "dining" },
      { label: "Jacuzzi", icon: "FaHotTub", category: "bathroom" },
      { label: "Living Area", icon: "FaCouch", category: "comfort" },
    ],
    includes: ["Breakfast", "Welcome Drink", "Airport Transfer"],
    tags: ["suite", "imperial", "luxury", "king", "ocean-view"],
    isAvailable: true,
    isPublished: true,
  },
  {
    name: "HIMALAYAS - 505",
    displayName: "HIMALAYAS - 505",
    slug: "imperial-suite-himalayas-505",
    roomNumber: "505",
    category: "Imperial Suite",
    pricePerNight: 58850,
    maxGuests: 4,
    maxAdults: 4,
    maxChildren: 0,
    bedType: "King",
    bedCount: 2,
    bathrooms: 2,
    size: "65 m²",
    sizeValue: 65,
    floor: 5,
    view: "Ocean View",
    description: "Luxurious imperial suite with premium amenities",
    longDescription:
      "Experience the ultimate luxury in our imperial suite with a Himalayas theme. Features include two king-sized beds, separate living area, premium amenities, and stunning ocean views.",
    amenities: [
      { label: "WiFi", icon: "FaWifi", category: "technology" },
      { label: "Air Conditioning", icon: "FaSnowflake", category: "comfort" },
      { label: "Flat-screen TV", icon: "FaTv", category: "technology" },
      { label: "Mini Bar", icon: "FaGlassCheers", category: "dining" },
      { label: "Jacuzzi", icon: "FaHotTub", category: "bathroom" },
      { label: "Living Area", icon: "FaCouch", category: "comfort" },
    ],
    includes: ["Breakfast", "Welcome Drink", "Airport Transfer"],
    tags: ["suite", "imperial", "luxury", "king", "ocean-view"],
    isAvailable: true,
    isPublished: true,
  },
  {
    name: "MASERATI - 205",
    displayName: "MASERATI - 205",
    slug: "imperial-suite-maserati-205",
    roomNumber: "205",
    category: "Imperial Suite",
    pricePerNight: 58850,
    maxGuests: 4,
    maxAdults: 4,
    maxChildren: 0,
    bedType: "King",
    bedCount: 2,
    bathrooms: 2,
    size: "65 m²",
    sizeValue: 65,
    floor: 2,
    view: "Ocean View",
    description: "Luxurious imperial suite with premium amenities",
    longDescription:
      "Experience the ultimate luxury in our imperial suite with a Maserati theme. Features include two king-sized beds, separate living area, premium amenities, and stunning ocean views.",
    amenities: [
      { label: "WiFi", icon: "FaWifi", category: "technology" },
      { label: "Air Conditioning", icon: "FaSnowflake", category: "comfort" },
      { label: "Flat-screen TV", icon: "FaTv", category: "technology" },
      { label: "Mini Bar", icon: "FaGlassCheers", category: "dining" },
      { label: "Jacuzzi", icon: "FaHotTub", category: "bathroom" },
      { label: "Living Area", icon: "FaCouch", category: "comfort" },
    ],
    includes: ["Breakfast", "Welcome Drink", "Airport Transfer"],
    tags: ["suite", "imperial", "luxury", "king", "ocean-view"],
    isAvailable: true,
    isPublished: true,
  },
  {
    name: "AJAX - 210",
    displayName: "AJAX - 210",
    slug: "annex-studio-ajax-210",
    roomNumber: "210",
    category: "Annex - Studio",
    pricePerNight: 21400,
    maxGuests: 2,
    maxAdults: 2,
    maxChildren: 0,
    bedType: "Queen",
    bedCount: 1,
    bathrooms: 1,
    size: "30 m²",
    sizeValue: 30,
    floor: 2,
    view: "Garden View",
    description: "Spacious studio in annex with modern amenities",
    longDescription:
      "Enjoy our spacious studio in the annex with an Ajax theme. Features include a comfortable queen-sized bed, kitchenette, and modern furnishings.",
    amenities: [
      { label: "WiFi", icon: "FaWifi", category: "technology" },
      { label: "Air Conditioning", icon: "FaSnowflake", category: "comfort" },
      { label: "Flat-screen TV", icon: "FaTv", category: "technology" },
      { label: "Kitchenette", icon: "FaKitchenSet", category: "dining" },
    ],
    includes: ["Breakfast"],
    tags: ["annex", "studio", "football-theme"],
    isAvailable: true,
    isPublished: true,
  },
  {
    name: "ARSENAL - 102",
    displayName: "ARSENAL - 102",
    slug: "annex-studio-arsenal-102",
    roomNumber: "102",
    category: "Annex - Studio",
    pricePerNight: 21400,
    maxGuests: 2,
    maxAdults: 2,
    maxChildren: 0,
    bedType: "Queen",
    bedCount: 1,
    bathrooms: 1,
    size: "30 m²",
    sizeValue: 30,
    floor: 1,
    view: "Garden View",
    description: "Spacious studio in annex with modern amenities",
    longDescription:
      "Enjoy our spacious studio in the annex with an Arsenal theme. Features include a comfortable queen-sized bed, kitchenette, and modern furnishings.",
    amenities: [
      { label: "WiFi", icon: "FaWifi", category: "technology" },
      { label: "Air Conditioning", icon: "FaSnowflake", category: "comfort" },
      { label: "Flat-screen TV", icon: "FaTv", category: "technology" },
      { label: "Kitchenette", icon: "FaKitchenSet", category: "dining" },
    ],
    includes: ["Breakfast"],
    tags: ["annex", "studio", "football-theme"],
    isAvailable: true,
    isPublished: true,
  },
  {
    name: "CRYSTAL PALACE - 211",
    displayName: "CRYSTAL PALACE - 211",
    slug: "annex-studio-crystal-211",
    roomNumber: "211",
    category: "Annex - Studio",
    pricePerNight: 21400,
    maxGuests: 2,
    maxAdults: 2,
    maxChildren: 0,
    bedType: "Queen",
    bedCount: 1,
    bathrooms: 1,
    size: "30 m²",
    sizeValue: 30,
    floor: 2,
    view: "Garden View",
    description: "Spacious studio in annex with modern amenities",
    longDescription:
      "Enjoy our spacious studio in the annex with a Crystal Palace theme. Features include a comfortable queen-sized bed, kitchenette, and modern furnishings.",
    amenities: [
      { label: "WiFi", icon: "FaWifi", category: "technology" },
      { label: "Air Conditioning", icon: "FaSnowflake", category: "comfort" },
      { label: "Flat-screen TV", icon: "FaTv", category: "technology" },
      { label: "Kitchenette", icon: "FaKitchenSet", category: "dining" },
    ],
    includes: ["Breakfast"],
    tags: ["annex", "studio", "football-theme"],
    isAvailable: true,
    isPublished: true,
  },
  {
    name: "INTER MILAN - 107",
    displayName: "INTER MILAN - 107",
    slug: "annex-studio-inter-107",
    roomNumber: "107",
    category: "Annex - Studio",
    pricePerNight: 21400,
    maxGuests: 2,
    maxAdults: 2,
    maxChildren: 0,
    bedType: "Queen",
    bedCount: 1,
    bathrooms: 1,
    size: "30 m²",
    sizeValue: 30,
    floor: 1,
    view: "Garden View",
    description: "Spacious studio in annex with modern amenities",
    longDescription:
      "Enjoy our spacious studio in the annex with an Inter Milan theme. Features include a comfortable queen-sized bed, kitchenette, and modern furnishings.",
    amenities: [
      { label: "WiFi", icon: "FaWifi", category: "technology" },
      { label: "Air Conditioning", icon: "FaSnowflake", category: "comfort" },
      { label: "Flat-screen TV", icon: "FaTv", category: "technology" },
      { label: "Kitchenette", icon: "FaKitchenSet", category: "dining" },
    ],
    includes: ["Breakfast"],
    tags: ["annex", "studio", "football-theme"],
    isAvailable: true,
    isPublished: true,
  },
  {
    name: "MAN UNITED - 201",
    displayName: "MAN UNITED - 201",
    slug: "annex-studio-manutd-201",
    roomNumber: "201",
    category: "Annex - Studio",
    pricePerNight: 21400,
    maxGuests: 2,
    maxAdults: 2,
    maxChildren: 0,
    bedType: "Queen",
    bedCount: 1,
    bathrooms: 1,
    size: "30 m²",
    sizeValue: 30,
    floor: 2,
    view: "Garden View",
    description: "Spacious studio in annex with modern amenities",
    longDescription:
      "Enjoy our spacious studio in the annex with a Manchester United theme. Features include a comfortable queen-sized bed, kitchenette, and modern furnishings.",
    amenities: [
      { label: "WiFi", icon: "FaWifi", category: "technology" },
      { label: "Air Conditioning", icon: "FaSnowflake", category: "comfort" },
      { label: "Flat-screen TV", icon: "FaTv", category: "technology" },
      { label: "Kitchenette", icon: "FaKitchenSet", category: "dining" },
    ],
    includes: ["Breakfast"],
    tags: ["annex", "studio", "football-theme"],
    isAvailable: true,
    isPublished: true,
  },
  {
    name: "ARIES - 602",
    displayName: "ARIES - 602",
    slug: "deluxe-aries-602",
    roomNumber: "602",
    category: "Deluxe",
    pricePerNight: 26750,
    maxGuests: 2,
    maxAdults: 2,
    maxChildren: 0,
    bedType: "Queen",
    bedCount: 1,
    bathrooms: 1,
    size: "35 m²",
    sizeValue: 35,
    floor: 6,
    view: "City View",
    description: "Deluxe room with premium amenities",
    longDescription:
      "Experience comfort in our deluxe room with an Aries theme. Features include a comfortable queen-sized bed, premium amenities, and elegant furnishings.",
    amenities: [
      { label: "WiFi", icon: "FaWifi", category: "technology" },
      { label: "Air Conditioning", icon: "FaSnowflake", category: "comfort" },
      { label: "Flat-screen TV", icon: "FaTv", category: "technology" },
      { label: "Mini Bar", icon: "FaGlassCheers", category: "dining" },
      { label: "Work Desk", icon: "FaDesk", category: "comfort" },
    ],
    includes: ["Breakfast"],
    tags: ["deluxe", "queen", "zodiac-theme"],
    isAvailable: true,
    isPublished: true,
  },
  {
    name: "AURORA - 603",
    displayName: "AURORA - 603",
    slug: "deluxe-aurora-603",
    roomNumber: "603",
    category: "Deluxe",
    pricePerNight: 26750,
    maxGuests: 2,
    maxAdults: 2,
    maxChildren: 0,
    bedType: "Queen",
    bedCount: 1,
    bathrooms: 1,
    size: "35 m²",
    sizeValue: 35,
    floor: 6,
    view: "City View",
    description: "Deluxe room with premium amenities",
    longDescription:
      "Experience comfort in our deluxe room with an Aurora theme. Features include a comfortable queen-sized bed, premium amenities, and elegant furnishings.",
    amenities: [
      { label: "WiFi", icon: "FaWifi", category: "technology" },
      { label: "Air Conditioning", icon: "FaSnowflake", category: "comfort" },
      { label: "Flat-screen TV", icon: "FaTv", category: "technology" },
      { label: "Mini Bar", icon: "FaGlassCheers", category: "dining" },
      { label: "Work Desk", icon: "FaDesk", category: "comfort" },
    ],
    includes: ["Breakfast"],
    tags: ["deluxe", "queen", "aurora-theme"],
    isAvailable: true,
    isPublished: true,
  },
  {
    name: "BAHAMAS - 502",
    displayName: "BAHAMAS - 502",
    slug: "deluxe-bahamas-502",
    roomNumber: "502",
    category: "Deluxe",
    pricePerNight: 26750,
    maxGuests: 2,
    maxAdults: 2,
    maxChildren: 0,
    bedType: "Queen",
    bedCount: 1,
    bathrooms: 1,
    size: "35 m²",
    sizeValue: 35,
    floor: 5,
    view: "City View",
    description: "Deluxe room with premium amenities",
    longDescription:
      "Experience comfort in our deluxe room with a Bahamas theme. Features include a comfortable queen-sized bed, premium amenities, and elegant furnishings.",
    amenities: [
      { label: "WiFi", icon: "FaWifi", category: "technology" },
      { label: "Air Conditioning", icon: "FaSnowflake", category: "comfort" },
      { label: "Flat-screen TV", icon: "FaTv", category: "technology" },
      { label: "Mini Bar", icon: "FaGlassCheers", category: "dining" },
      { label: "Work Desk", icon: "FaDesk", category: "comfort" },
    ],
    includes: ["Breakfast"],
    tags: ["deluxe", "queen", "island-theme"],
    isAvailable: true,
    isPublished: true,
  },
  {
    name: "BALI - 503",
    displayName: "BALI - 503",
    slug: "deluxe-bali-503",
    roomNumber: "503",
    category: "Deluxe",
    pricePerNight: 26750,
    maxGuests: 2,
    maxAdults: 2,
    maxChildren: 0,
    bedType: "Queen",
    bedCount: 1,
    bathrooms: 1,
    size: "35 m²",
    sizeValue: 35,
    floor: 5,
    view: "City View",
    description: "Deluxe room with premium amenities",
    longDescription:
      "Experience comfort in our deluxe room with a Bali theme. Features include a comfortable queen-sized bed, premium amenities, and elegant furnishings.",
    amenities: [
      { label: "WiFi", icon: "FaWifi", category: "technology" },
      { label: "Air Conditioning", icon: "FaSnowflake", category: "comfort" },
      { label: "Flat-screen TV", icon: "FaTv", category: "technology" },
      { label: "Mini Bar", icon: "FaGlassCheers", category: "dining" },
      { label: "Work Desk", icon: "FaDesk", category: "comfort" },
    ],
    includes: ["Breakfast"],
    tags: ["deluxe", "queen", "island-theme"],
    isAvailable: true,
    isPublished: true,
  },
  {
    name: "BARBADOS - 504",
    displayName: "BARBADOS - 504",
    slug: "deluxe-barbados-504",
    roomNumber: "504",
    category: "Deluxe",
    pricePerNight: 26750,
    maxGuests: 2,
    maxAdults: 2,
    maxChildren: 0,
    bedType: "Queen",
    bedCount: 1,
    bathrooms: 1,
    size: "35 m²",
    sizeValue: 35,
    floor: 5,
    view: "City View",
    description: "Deluxe room with premium amenities",
    longDescription:
      "Experience comfort in our deluxe room with a Barbados theme. Features include a comfortable queen-sized bed, premium amenities, and elegant furnishings.",
    amenities: [
      { label: "WiFi", icon: "FaWifi", category: "technology" },
      { label: "Air Conditioning", icon: "FaSnowflake", category: "comfort" },
      { label: "Flat-screen TV", icon: "FaTv", category: "technology" },
      { label: "Mini Bar", icon: "FaGlassCheers", category: "dining" },
      { label: "Work Desk", icon: "FaDesk", category: "comfort" },
    ],
    includes: ["Breakfast"],
    tags: ["deluxe", "queen", "island-theme"],
    isAvailable: true,
    isPublished: true,
  },
  {
    name: "BLUE - 302",
    displayName: "BLUE - 302",
    slug: "deluxe-blue-302",
    roomNumber: "302",
    category: "Deluxe",
    pricePerNight: 26750,
    maxGuests: 2,
    maxAdults: 2,
    maxChildren: 0,
    bedType: "Queen",
    bedCount: 1,
    bathrooms: 1,
    size: "35 m²",
    sizeValue: 35,
    floor: 3,
    view: "City View",
    description: "Deluxe room with premium amenities",
    longDescription:
      "Experience comfort in our deluxe room with a blue theme. Features include a comfortable queen-sized bed, premium amenities, and elegant furnishings.",
    amenities: [
      { label: "WiFi", icon: "FaWifi", category: "technology" },
      { label: "Air Conditioning", icon: "FaSnowflake", category: "comfort" },
      { label: "Flat-screen TV", icon: "FaTv", category: "technology" },
      { label: "Mini Bar", icon: "FaGlassCheers", category: "dining" },
      { label: "Work Desk", icon: "FaDesk", category: "comfort" },
    ],
    includes: ["Breakfast"],
    tags: ["deluxe", "queen", "color-theme"],
    isAvailable: true,
    isPublished: true,
  },
  {
    name: "BROWN - 303",
    displayName: "BROWN - 303",
    slug: "deluxe-brown-303",
    roomNumber: "303",
    category: "Deluxe",
    pricePerNight: 26750,
    maxGuests: 2,
    maxAdults: 2,
    maxChildren: 0,
    bedType: "Queen",
    bedCount: 1,
    bathrooms: 1,
    size: "35 m²",
    sizeValue: 35,
    floor: 3,
    view: "City View",
    description: "Deluxe room with premium amenities",
    longDescription:
      "Experience comfort in our deluxe room with a brown theme. Features include a comfortable queen-sized bed, premium amenities, and elegant furnishings.",
    amenities: [
      { label: "WiFi", icon: "FaWifi", category: "technology" },
      { label: "Air Conditioning", icon: "FaSnowflake", category: "comfort" },
      { label: "Flat-screen TV", icon: "FaTv", category: "technology" },
      { label: "Mini Bar", icon: "FaGlassCheers", category: "dining" },
      { label: "Work Desk", icon: "FaDesk", category: "comfort" },
    ],
    includes: ["Breakfast"],
    tags: ["deluxe", "queen", "color-theme"],
    isAvailable: true,
    isPublished: true,
  },
  {
    name: "BUGATTI - 202",
    displayName: "BUGATTI - 202",
    slug: "deluxe-bugatti-202",
    roomNumber: "202",
    category: "Deluxe",
    pricePerNight: 26750,
    maxGuests: 2,
    maxAdults: 2,
    maxChildren: 0,
    bedType: "Queen",
    bedCount: 1,
    bathrooms: 1,
    size: "35 m²",
    sizeValue: 35,
    floor: 2,
    view: "City View",
    description: "Deluxe room with premium amenities",
    longDescription:
      "Experience comfort in our deluxe room with a Bugatti theme. Features include a comfortable queen-sized bed, premium amenities, and elegant furnishings.",
    amenities: [
      { label: "WiFi", icon: "FaWifi", category: "technology" },
      { label: "Air Conditioning", icon: "FaSnowflake", category: "comfort" },
      { label: "Flat-screen TV", icon: "FaTv", category: "technology" },
      { label: "Mini Bar", icon: "FaGlassCheers", category: "dining" },
      { label: "Work Desk", icon: "FaDesk", category: "comfort" },
    ],
    includes: ["Breakfast"],
    tags: ["deluxe", "queen", "car-theme"],
    isAvailable: true,
    isPublished: true,
  },
  {
    name: "BURGUNDY - 304",
    displayName: "BURGUNDY - 304",
    slug: "deluxe-burgundy-304",
    roomNumber: "304",
    category: "Deluxe",
    pricePerNight: 26750,
    maxGuests: 2,
    maxAdults: 2,
    maxChildren: 0,
    bedType: "Queen",
    bedCount: 1,
    bathrooms: 1,
    size: "35 m²",
    sizeValue: 35,
    floor: 3,
    view: "City View",
    description: "Deluxe room with premium amenities",
    longDescription:
      "Experience comfort in our deluxe room with a burgundy theme. Features include a comfortable queen-sized bed, premium amenities, and elegant furnishings.",
    amenities: [
      { label: "WiFi", icon: "FaWifi", category: "technology" },
      { label: "Air Conditioning", icon: "FaSnowflake", category: "comfort" },
      { label: "Flat-screen TV", icon: "FaTv", category: "technology" },
      { label: "Mini Bar", icon: "FaGlassCheers", category: "dining" },
      { label: "Work Desk", icon: "FaDesk", category: "comfort" },
    ],
    includes: ["Breakfast"],
    tags: ["deluxe", "queen", "color-theme"],
    isAvailable: true,
    isPublished: true,
  },
  {
    name: "CAPELLA - 604",
    displayName: "CAPELLA - 604",
    slug: "deluxe-capella-604",
    roomNumber: "604",
    category: "Deluxe",
    pricePerNight: 26750,
    maxGuests: 2,
    maxAdults: 2,
    maxChildren: 0,
    bedType: "Queen",
    bedCount: 1,
    bathrooms: 1,
    size: "35 m²",
    sizeValue: 35,
    floor: 6,
    view: "City View",
    description: "Deluxe room with premium amenities",
    longDescription:
      "Experience comfort in our deluxe room with a Capella theme. Features include a comfortable queen-sized bed, premium amenities, and elegant furnishings.",
    amenities: [
      { label: "WiFi", icon: "FaWifi", category: "technology" },
      { label: "Air Conditioning", icon: "FaSnowflake", category: "comfort" },
      { label: "Flat-screen TV", icon: "FaTv", category: "technology" },
      { label: "Mini Bar", icon: "FaGlassCheers", category: "dining" },
      { label: "Work Desk", icon: "FaDesk", category: "comfort" },
    ],
    includes: ["Breakfast"],
    tags: ["deluxe", "queen", "star-theme"],
    isAvailable: true,
    isPublished: true,
  },
  {
    name: "CROW - 402",
    displayName: "CROW - 402",
    slug: "deluxe-crow-402",
    roomNumber: "402",
    category: "Deluxe",
    pricePerNight: 26750,
    maxGuests: 2,
    maxAdults: 2,
    maxChildren: 0,
    bedType: "Queen",
    bedCount: 1,
    bathrooms: 1,
    size: "35 m²",
    sizeValue: 35,
    floor: 4,
    view: "City View",
    description: "Deluxe room with premium amenities",
    longDescription:
      "Experience comfort in our deluxe room with a crow theme. Features include a comfortable queen-sized bed, premium amenities, and elegant furnishings.",
    amenities: [
      { label: "WiFi", icon: "FaWifi", category: "technology" },
      { label: "Air Conditioning", icon: "FaSnowflake", category: "comfort" },
      { label: "Flat-screen TV", icon: "FaTv", category: "technology" },
      { label: "Mini Bar", icon: "FaGlassCheers", category: "dining" },
      { label: "Work Desk", icon: "FaDesk", category: "comfort" },
    ],
    includes: ["Breakfast"],
    tags: ["deluxe", "queen", "bird-theme"],
    isAvailable: true,
    isPublished: true,
  },
  {
    name: "DOVE - 403",
    displayName: "DOVE - 403",
    slug: "deluxe-dove-403",
    roomNumber: "403",
    category: "Deluxe",
    pricePerNight: 26750,
    maxGuests: 2,
    maxAdults: 2,
    maxChildren: 0,
    bedType: "Queen",
    bedCount: 1,
    bathrooms: 1,
    size: "35 m²",
    sizeValue: 35,
    floor: 4,
    view: "City View",
    description: "Deluxe room with premium amenities",
    longDescription:
      "Experience comfort in our deluxe room with a dove theme. Features include a comfortable queen-sized bed, premium amenities, and elegant furnishings.",
    amenities: [
      { label: "WiFi", icon: "FaWifi", category: "technology" },
      { label: "Air Conditioning", icon: "FaSnowflake", category: "comfort" },
      { label: "Flat-screen TV", icon: "FaTv", category: "technology" },
      { label: "Mini Bar", icon: "FaGlassCheers", category: "dining" },
      { label: "Work Desk", icon: "FaDesk", category: "comfort" },
    ],
    includes: ["Breakfast"],
    tags: ["deluxe", "queen", "bird-theme"],
    isAvailable: true,
    isPublished: true,
  },
  {
    name: "EAGLE - 404",
    displayName: "EAGLE - 404",
    slug: "deluxe-eagle-404",
    roomNumber: "404",
    category: "Deluxe",
    pricePerNight: 26750,
    maxGuests: 2,
    maxAdults: 2,
    maxChildren: 0,
    bedType: "Queen",
    bedCount: 1,
    bathrooms: 1,
    size: "35 m²",
    sizeValue: 35,
    floor: 4,
    view: "City View",
    description: "Deluxe room with premium amenities",
    longDescription:
      "Experience comfort in our deluxe room with an eagle theme. Features include a comfortable queen-sized bed, premium amenities, and elegant furnishings.",
    amenities: [
      { label: "WiFi", icon: "FaWifi", category: "technology" },
      { label: "Air Conditioning", icon: "FaSnowflake", category: "comfort" },
      { label: "Flat-screen TV", icon: "FaTv", category: "technology" },
      { label: "Mini Bar", icon: "FaGlassCheers", category: "dining" },
      { label: "Work Desk", icon: "FaDesk", category: "comfort" },
    ],
    includes: ["Breakfast"],
    tags: ["deluxe", "queen", "bird-theme"],
    isAvailable: true,
    isPublished: true,
  },
  {
    name: "FERRARI - 203",
    displayName: "FERRARI - 203",
    slug: "deluxe-ferrari-203",
    roomNumber: "203",
    category: "Deluxe",
    pricePerNight: 26750,
    maxGuests: 2,
    maxAdults: 2,
    maxChildren: 0,
    bedType: "Queen",
    bedCount: 1,
    bathrooms: 1,
    size: "35 m²",
    sizeValue: 35,
    floor: 2,
    view: "City View",
    description: "Deluxe room with premium amenities",
    longDescription:
      "Experience comfort in our deluxe room with a Ferrari theme. Features include a comfortable queen-sized bed, premium amenities, and elegant furnishings.",
    amenities: [
      { label: "WiFi", icon: "FaWifi", category: "technology" },
      { label: "Air Conditioning", icon: "FaSnowflake", category: "comfort" },
      { label: "Flat-screen TV", icon: "FaTv", category: "technology" },
      { label: "Mini Bar", icon: "FaGlassCheers", category: "dining" },
      { label: "Work Desk", icon: "FaDesk", category: "comfort" },
    ],
    includes: ["Breakfast"],
    tags: ["deluxe", "queen", "car-theme"],
    isAvailable: true,
    isPublished: true,
  },
  {
    name: "LAMBORGHINI - 204",
    displayName: "LAMBORGHINI - 204",
    slug: "deluxe-lamborghini-204",
    roomNumber: "204",
    category: "Deluxe",
    pricePerNight: 26750,
    maxGuests: 2,
    maxAdults: 2,
    maxChildren: 0,
    bedType: "Queen",
    bedCount: 1,
    bathrooms: 1,
    size: "35 m²",
    sizeValue: 35,
    floor: 2,
    view: "City View",
    description: "Deluxe room with premium amenities",
    longDescription:
      "Experience comfort in our deluxe room with a Lamborghini theme. Features include a comfortable queen-sized bed, premium amenities, and elegant furnishings.",
    amenities: [
      { label: "WiFi", icon: "FaWifi", category: "technology" },
      { label: "Air Conditioning", icon: "FaSnowflake", category: "comfort" },
      { label: "Flat-screen TV", icon: "FaTv", category: "technology" },
      { label: "Mini Bar", icon: "FaGlassCheers", category: "dining" },
      { label: "Work Desk", icon: "FaDesk", category: "comfort" },
    ],
    includes: ["Breakfast"],
    tags: ["deluxe", "queen", "car-theme"],
    isAvailable: true,
    isPublished: true,
  },
  {
    name: "MAURITIUS - 509",
    displayName: "MAURITIUS - 509",
    slug: "superior-twin-mauritius-509",
    roomNumber: "509",
    category: "Superior Twin",
    pricePerNight: 48150,
    maxGuests: 3,
    maxAdults: 3,
    maxChildren: 0,
    bedType: "Twin",
    bedCount: 2,
    bathrooms: 1,
    size: "40 m²",
    sizeValue: 40,
    floor: 5,
    view: "City View",
    description: "Spacious superior twin room with two beds",
    longDescription:
      "Enjoy our spacious superior twin room with two comfortable beds, perfect for families or groups. Features include modern amenities and elegant furnishings with a Mauritius theme.",
    amenities: [
      { label: "WiFi", icon: "FaWifi", category: "technology" },
      { label: "Air Conditioning", icon: "FaSnowflake", category: "comfort" },
      { label: "Flat-screen TV", icon: "FaTv", category: "technology" },
      { label: "Mini Bar", icon: "FaGlassCheers", category: "dining" },
      { label: "Work Desk", icon: "FaDesk", category: "comfort" },
      { label: "Sitting Area", icon: "FaCouch", category: "comfort" },
    ],
    includes: ["Breakfast", "Welcome Drink"],
    tags: ["superior", "twin", "island-theme"],
    isAvailable: true,
    isPublished: true,
  },
];

// Configuration
const API_URL = process.env.API_URL || "http://localhost:5000";
const ADMIN_TOKEN =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRGF0YSI6eyJfaWQiOiI2OTlkZjA4ZDkyMDE1OTM2NWI0ZWQ3M2UiLCJyb2xlIjoiYWRtaW4iLCJlbWFpbCI6InBldGVyc29uem9jb25pc0BnbWFpbC5jb20ifSwic2Vzc2lvbiI6IjY5YTE2ODczYjhhMDhkZjJkNGFjYzU5ZCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc3MjE4NTcxNSwiZXhwIjoxNzcyMjcyMTE1fQ.Zg9ROcv1VjRQezeSWbFG6w_uuX85Vbr9GyieUcEiU2g";

// Stats tracker
const stats = {
  total: rooms.length,
  success: 0,
  failed: [],
  skipped: [],
};

async function seedRooms() {
  console.log("🚀 Starting room seeding...");
  console.log(`📊 Total rooms to process: ${stats.total}`);
  console.log("----------------------------------------\n");

  for (let i = 0; i < rooms.length; i++) {
    const room = { ...rooms[i], sortOrder: i + 1 };
    const progress = `[${i + 1}/${stats.total}]`;

    try {
      // Add delay to avoid overwhelming the server (500ms between requests)
      if (i > 0) {
        await new Promise((resolve) => setTimeout(resolve, 500));
      }

      console.log(
        `${progress} Creating room: ${room.name} (${room.category})...`,
      );

      const response = await axios.post(`${API_URL}/admin/rooms`, room, {
        headers: {
          Authorization: `Bearer ${ADMIN_TOKEN}`,
          "Content-Type": "application/json",
        },
      });

      if (response.data.status === "success") {
        stats.success++;
        console.log(`✅ SUCCESS: ${room.name} created successfully`);
      } else {
        throw new Error(response.data.message || "Unknown error");
      }
    } catch (error) {
      // Handle duplicate slug errors
      if (error.response?.status === 409) {
        stats.skipped.push({
          name: room.name,
          reason: "Duplicate slug - already exists",
        });
        console.log(`⚠️ SKIPPED: ${room.name} - Already exists`);
      } else {
        stats.failed.push({
          name: room.name,
          error: error.response?.data?.message || error.message,
        });
        console.log(
          `❌ FAILED: ${room.name} - ${error.response?.data?.message || error.message}`,
        );
      }
    }

    // Show progress every 5 rooms
    if ((i + 1) % 5 === 0 || i === rooms.length - 1) {
      console.log(
        `\n📈 Progress: ${stats.success} successful, ${stats.failed.length} failed, ${stats.skipped.length} skipped\n`,
      );
    }
  }

  // Final report
  console.log("\n🎉 ===== SEEDING COMPLETE ===== 🎉");
  console.log(`📊 Final Results:`);
  console.log(`   ✅ Successful: ${stats.success}`);
  console.log(`   ❌ Failed: ${stats.failed.length}`);
  console.log(`   ⚠️ Skipped (duplicates): ${stats.skipped.length}`);

  if (stats.failed.length > 0) {
    console.log("\n❌ Failed Rooms:");
    stats.failed.forEach((f) => {
      console.log(`   - ${f.name}: ${f.error}`);
    });
  }

  if (stats.skipped.length > 0) {
    console.log("\n⚠️ Skipped Rooms (already exist):");
    stats.skipped.forEach((s) => {
      console.log(`   - ${s.name}`);
    });
  }
}

// Run the seeding
seedRooms().catch(console.error);
